### ISSUE TITLE
parent项目的pom以及子的依赖是否有问题

### ISSUE THREAD

**Issue by justein** [xuminwlt/j360-dubbo-app-all#1]
各子项目的依赖关系没有，而且父项目的pom没有添加依赖等配置
com.pajk.ic.*这个依赖是否有说明？

**Comment by xuminwlt** [comment]
部分代码源于线上的代码，并没有整合完整，近期会逐步整合

**Comment by justein** [comment]
@xuminwlt 好的，期待！
